# Global configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Resume Relevance System monitoring
  - job_name: "resume-relevance-app"
    static_configs:
      - targets: ["app:5000"]
    metrics_path: "/metrics"
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL monitoring (if using postgres_exporter)
  - job_name: "postgresql"
    static_configs:
      - targets: ["db:5432"]
    scrape_interval: 30s

  # Redis monitoring (if using redis_exporter)
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 30s

  # Nginx monitoring (if using nginx-prometheus-exporter)
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:9113"]
    scrape_interval: 30s
